# 1. Import Necessary Library

In [1]:
# Name: Md Rashed Karim
# Student ID: 905242031
import numpy as np

# 2. Numpy Array
i) Create 2 numpy 1D array (arr1,arr2) and populate data using random library function

In [19]:
arr1 = np.random.randint(15,size=5)
arr1

array([ 4, 10,  1, 10,  3])

In [21]:
arr2 = np.random.randint(20, 50, size=5)
arr2

array([42, 49, 29, 24, 37])

ii) Find out all the unique values from both arrays and print the output in a sorted manner

In [45]:
np.sort(np.unique(arr1))

array([ 1,  3,  4, 10])

In [43]:
np.sort(np.unique(arr2))

array([24, 29, 37, 42, 49])

iii) Find out the summation of all even numbers of these arrays

In [47]:
even_arr1 = arr1[arr1 % 2 == 0].sum()
even_arr1

24

In [49]:
even_arr2 = arr2[arr2 % 2 == 0].sum()
even_arr2

66

iv) Create a 2D array combining this 2 array

In [63]:
d2 = np.vstack((arr1, arr2))
d2

array([[ 4, 10,  1, 10,  3],
       [42, 49, 29, 24, 37]])

v) Find the maximum value of each column

In [65]:
column_max = np.max(d2, axis=0)
column_max

array([42, 49, 29, 24, 37])

# 3. Pandas
i) import data from provided file and display

In [167]:
import pandas as pd
df = pd.read_csv("movie.csv")
df

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Signed Sealed Delivered,2013.0,Color,NaN,87.0,Scott Smith,2.0,Eric Mabius,637.0,Daphne Zuniga,...,318.0,NaN,Comedy|Drama,1.0,629,fraud|postal worker|prison|theft|trial,English,Canada,NaN,7.7
4912,The Following,NaN,Color,TV-14,43.0,NaN,NaN,Natalie Zea,841.0,Valorie Curry,...,319.0,NaN,Crime|Drama|Mystery|Thriller,43.0,73839,cult|fbi|hideout|prison escape|serial killer,English,USA,NaN,7.5
4913,A Plague So Pleasant,2013.0,Color,NaN,76.0,Benjamin Roberds,0.0,Eva Boehnke,0.0,Maxwell Moody,...,0.0,NaN,Drama|Horror|Thriller,13.0,38,NaN,English,USA,1400.0,6.3
4914,Shanghai Calling,2012.0,Color,PG-13,100.0,Daniel Hsia,0.0,Alan Ruck,946.0,Daniel Henney,...,489.0,10443.0,Comedy|Drama|Romance,14.0,1255,NaN,English,USA,NaN,6.3
4915,My Date with Drew,2004.0,Color,PG,90.0,Jon Gunn,16.0,John August,86.0,Brian Herzlinger,...,16.0,85222.0,Documentary,43.0,4285,actress name in title|crush|date|four word tit...,English,USA,1100.0,6.6

ii) Do the necessary for missing value handling apply appropriate technique

In [169]:
print("Missing values in the DataFrame:")
df.isnull()

Missing values in the DataFrame:

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,True,True,True,True,False,False,False,False,False,...,True,True,False,True,False,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,False,False,False,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4912,False,True,False,False,False,True,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4913,False,False,False,True,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,False,False
4914,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
4915,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [171]:
df.dropna()

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
5,John Carter,2012.0,Color,PG-13,132.0,Andrew Stanton,475.0,Daryl Sabara,640.0,Samantha Morton,...,530.0,73058679.0,Action|Adventure|Sci-Fi,462.0,212204,alien|american civil war|male nipple|mars|prin...,English,USA,263700000.0,6.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4906,Primer,2004.0,Color,PG-13,77.0,Shane Carruth,291.0,Shane Carruth,291.0,David Sullivan,...,8.0,424760.0,Drama|Sci-Fi|Thriller,143.0,72639,changing the future|independent film|invention...,English,USA,7000.0,7.0
4907,Cavite,2005.0,Color,Not Rated,80.0,Neill Dela Llana,0.0,Ian Gamazon,0.0,Edgar Tancangco,...,0.0,70071.0,Thriller,35.0,589,jihad|mindanao|philippines|security guard|squa...,English,Philippines,7000.0,6.3
4908,El Mariachi,1992.0,Color,R,81.0,Robert Rodriguez,0.0,Carlos Gallardo,121.0,Peter Marquardt,...,6.0,2040920.0,Action|Crime|Drama|Romance|Thriller,56.0,52055,assassin|death|guitar|gun|mariachi,Spanish,USA,7000.0,6.9
4910,Newlyweds,2011.0,Color,Not Rated,95.0,Edward Burns,0.0,Kerry Bishé,296.0,Caitlin FitzGerald,...,133.0,4584.0,Comedy|Drama,14.0,1338,written and directed by cast member,English,USA,9000.0,6.4
4915,My Date with Drew,2004.0,Color,PG,90.0,Jon Gunn,16.0,John August,86.0,Brian Herzlinger,...,16.0,85222.0,Documentary,43.0,4285,actress name in title|crush|date|four word tit...,English,USA,1100.0,6.6

iii) Change inappropriate data type (if any)

In [173]:
df['year'] = df['year'] = df['year'].fillna(0).astype(int)
df

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
4,Star Wars: Episode VII - The Force Awakens,0,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Signed Sealed Delivered,2013,Color,NaN,87.0,Scott Smith,2.0,Eric Mabius,637.0,Daphne Zuniga,...,318.0,NaN,Comedy|Drama,1.0,629,fraud|postal worker|prison|theft|trial,English,Canada,NaN,7.7
4912,The Following,0,Color,TV-14,43.0,NaN,NaN,Natalie Zea,841.0,Valorie Curry,...,319.0,NaN,Crime|Drama|Mystery|Thriller,43.0,73839,cult|fbi|hideout|prison escape|serial killer,English,USA,NaN,7.5
4913,A Plague So Pleasant,2013,Color,NaN,76.0,Benjamin Roberds,0.0,Eva Boehnke,0.0,Maxwell Moody,...,0.0,NaN,Drama|Horror|Thriller,13.0,38,NaN,English,USA,1400.0,6.3
4914,Shanghai Calling,2012,Color,PG-13,100.0,Daniel Hsia,0.0,Alan Ruck,946.0,Daniel Henney,...,489.0,10443.0,Comedy|Drama|Romance,14.0,1255,NaN,English,USA,NaN,6.3
4915,My Date with Drew,2004,Color,PG,90.0,Jon Gunn,16.0,John August,86.0,Brian Herzlinger,...,16.0,85222.0,Documentary,43.0,4285,actress name in title|crush|date|four word tit...,English,USA,1100.0,6.6

iv) Rename the column with meaningful name (at least one column)

In [175]:
df.rename(columns={'title': 'Movie Name'})

,Movie Name,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
4,Star Wars: Episode VII - The Force Awakens,0,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Signed Sealed Delivered,2013,Color,NaN,87.0,Scott Smith,2.0,Eric Mabius,637.0,Daphne Zuniga,...,318.0,NaN,Comedy|Drama,1.0,629,fraud|postal worker|prison|theft|trial,English,Canada,NaN,7.7
4912,The Following,0,Color,TV-14,43.0,NaN,NaN,Natalie Zea,841.0,Valorie Curry,...,319.0,NaN,Crime|Drama|Mystery|Thriller,43.0,73839,cult|fbi|hideout|prison escape|serial killer,English,USA,NaN,7.5
4913,A Plague So Pleasant,2013,Color,NaN,76.0,Benjamin Roberds,0.0,Eva Boehnke,0.0,Maxwell Moody,...,0.0,NaN,Drama|Horror|Thriller,13.0,38,NaN,English,USA,1400.0,6.3
4914,Shanghai Calling,2012,Color,PG-13,100.0,Daniel Hsia,0.0,Alan Ruck,946.0,Daniel Henney,...,489.0,10443.0,Comedy|Drama|Romance,14.0,1255,NaN,English,USA,NaN,6.3
4915,My Date with Drew,2004,Color,PG,90.0,Jon Gunn,16.0,John August,86.0,Brian Herzlinger,...,16.0,85222.0,Documentary,43.0,4285,actress name in title|crush|date|four word tit...,English,USA,1100.0,6.6

v) Select the highest budgeted movie

In [177]:
df[df['budget'] == df['budget'].max()]

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
3787,Lady Vengeance,2005,Color,R,112.0,Chan-wook Park,0.0,Min-sik Choi,717.0,Yeong-ae Lee,...,38.0,211667.0,Crime|Drama,202.0,53508,cake|christian|lesbian sex|oral sex|pregnant s...,Korean,South Korea,4.200000e+09,7.7

vi) Select the best 10 movies according their imdb score

In [179]:
df.head(10)

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
4,Star Wars: Episode VII - The Force Awakens,0,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1
5,John Carter,2012,Color,PG-13,132.0,Andrew Stanton,475.0,Daryl Sabara,640.0,Samantha Morton,...,530.0,73058679.0,Action|Adventure|Sci-Fi,462.0,212204,alien|american civil war|male nipple|mars|prin...,English,USA,263700000.0,6.6
6,Spider-Man 3,2007,Color,PG-13,156.0,Sam Raimi,0.0,J.K. Simmons,24000.0,James Franco,...,4000.0,336530303.0,Action|Adventure|Romance,392.0,383056,sandman|spider man|symbiote|venom|villain,English,USA,258000000.0,6.2
7,Tangled,2010,Color,PG,100.0,Nathan Greno,15.0,Brad Garrett,799.0,Donna Murphy,...,284.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,324.0,294810,17th century|based on fairy tale|disney|flower...,English,USA,260000000.0,7.8
8,Avengers: Age of Ultron,2015,Color,PG-13,141.0,Joss Whedon,0.0,Chris Hemsworth,26000.0,Robert Downey Jr.,...,19000.0,458991599.0,Action|Adventure|Sci-Fi,635.0,462669,artificial intelligence|based on comic book|ca...,English,USA,250000000.0,7.5
9,Harry Potter and the Half-Blood Prince,2009,Color,PG,153.0,David Yates,282.0,Alan Rickman,25000.0,Daniel Radcliffe,...,10000.0,301956980.0,Adventure|Family|Fantasy|Mystery,375.0,321795,blood|book|love|potion|professor,English,UK,250000000.0,7.5

vii) Select all the movies such that the Facebook likes for actor 2 are greater than those for
actor 1

In [199]:
# df.info()
df[df['actor2_fb'] > df['actor1_fb']]

Empty DataFrame
Columns: [title, year, color, content_rating, duration, director_name, director_fb, actor1, actor1_fb, actor2, actor2_fb, actor3, actor3_fb, gross, genres, num_reviews, num_voted_users, plot_keywords, language, country, budget, imdb_score]
Index: []

[0 rows x 22 columns]

viii) Find out the director who produced the highest number of movies

In [221]:
director_movie_count = df.groupby('director_name')['title'].count()
director_movie_count
top_director = director_movie_count.idxmax()
max_movies = director_movie_count.max()

print(f'The director: "{top_director}" who produced {max_movies} movies.')
# df[df['director_name'] > df['actor1_fb']]

The director: "Steven Spielberg" who produced 26 movies.